language: node_js
node_js:
  - '10'
  - '12'
install: yarn
script:
  - yarn test --coverage
  - yarn lint
  - yarn build
  - yarn docs:build
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh $RELEASE_NOTES_TOKEN
  on:
    branch: master
